language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
before_install: gem install bundler -v 1.4.0.pre.2 --pre
bundler_args: -j4 --deployment 
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec

env:
  global:
    - secure: ! 'XbVqaIM7QgEXh+Yjf+1NtlfCoNgge9PnwfuwrpoXGOpSnKTFa0AhX0A1Y0wKJKOpvXf6I2r6dBGS6gBXXFNo8iZwrVZD3gPOqTSs4GAqbUMFgYiEv3za0CheGliHeoa4G22G8MInPrHV8gFR7PjKz/yt1/QByNOTtg84RBknqiQ='
    
    
after_success:
  - ./heroku.sh
