language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
bundler_args: --deployment
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
env:
  global:
    - secure: "SpjpgL5v6Oug5eKqWRlGgMfxckxN64wm/8YbNtI+7fmvWQnqJxyEqt2Hrgug5v2Z70MkEGtKuc359tV7xz6i1xohQOMqAbnL+XMaldvyI5HJqOUYC0RvCSG1LLHHHgA2X5QxOx756Ul5F/uhaOLCjuYi8bAtuawrQYxPe7LhvIQ="
    
after_success:
  - ./heroku.sh
